[www]
user  = www-data
group = www-data

listen = 127.0.0.1:9000

; Dynamic — adapté à 4GB RAM, chaque worker ~45 MB
; 40 workers = ~1800 MB max, laisse de la marge pour DB/Redis/OS
pm                   = dynamic
pm.max_children      = 40
pm.start_servers     = 10
pm.min_spare_servers = 5
pm.max_spare_servers = 20
pm.max_requests      = 500

; Timeout
request_terminate_timeout = 60

; Logs
catch_workers_output       = yes
php_flag[display_errors]   = off
php_admin_value[error_log] = /dev/stderr
php_admin_flag[log_errors] = on

; Passer les variables d'env au processus PHP
clear_env = no
